<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends EntityRepository
{
    public function getAllBookOfIdGretenThen($id){

        $query = $this->getEntityManager()->createQuery('
            SELECT book FROM AppBundle:Book book WHERE book.id > :id
        ')->setParameter("id",$id );

        return $query->getResult();
    }
}
